cc_library(
    name = "dbfile_lib",
    srcs = glob(["*.cpp"]),        
    hdrs = glob(["*.hpp"]),          
    includes = [".",".."],         
    deps = ["//src:types_lib"],
    visibility = ["//visibility:public"],
)
