cc_library(
    name = "dbfile_lib",
    srcs = glob(["*.cpp"]),        
    hdrs = glob(["*.hpp"]),          
    includes = [".",".."],         
    deps = [
        "//src:types_lib",
        "//src:page_lib",
    ],
    visibility = ["//visibility:public"],
)
