cc_test(
    name = "pagecache_test",
    srcs = ["test_pagecache.cpp"],  # Your test files here
    deps = [
        "//src/PageCache:pagecache_lib",
        "//src:types_lib",       # Types.hpp
        "@googletest//:gtest_main",
    ],
)