cc_test(
    name = "dbfile_test",
    srcs = ["test_dbfile.cpp"],  # Your test files here
    deps = [
        "//src/DbFile:dbfile_lib",
        "//src:types_lib",       # Types.hpp
        "@googletest//:gtest_main",
    ],
)