cc_test(
    name = "dbfile_test",
    srcs = ["test_dbfile.cpp"],  # Your test files here
    deps = 
    [
        "//src/DbFile:dbfile_lib",
        "//src:page_lib",
        "//src:types_lib",    
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)