cc_test(
    name = "table_test",
    srcs = ["test_table.cpp"],
    deps = [
        "//src/Table:table_lib",
        "//src:types_lib", 
        "//src/PageCache:pagecache_lib",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)